#!/bin/bash
# Ultra-simple: LIDAR Only SLAM
# Scan Restamper + RF2O + SLAM Toolbox
# No motor odometry complexity

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "================================================"
echo "SLAM Toolbox - LIDAR Only (Scan-Only Mode)"
echo "================================================"

# Kill existing
pkill -f "slam_toolbox|rf2o|scan_rest|motor_odom|merger" 2>/dev/null || true
sleep 2

# 1. Static TF
echo "[1/4] Static Transform (base_link → laser_link)..."
ros2 run tf2_ros static_transform_publisher 0.10 0.0 0.15 0 0 0 base_link laser_link &
sleep 2

# 2. Scan Restamper
echo "[2/4] Scan Restamper..."
python3 scan_restamper_simple.py &
sleep 3

# 3. RF2O
echo "[3/4] RF2O Laser Odometry..."
ros2 run rf2o_laser_odometry rf2o_laser_odometry_node \
  --ros-args \
  -p scan_topic:=/scan \
  -p odom_topic:=/odom \
  -p base_frame_id:=base_link \
  -p odom_frame_id:=map \
  -p freq:=20.0 \
  -p publish_tf:=false &
sleep 3

# 4. SLAM Toolbox (scan-only mode - uses /scan only, ignores odom)
echo "[4/4] SLAM Toolbox (scan-only)..."
ros2 run slam_toolbox async_slam_toolbox_node \
  --ros-args \
  --params-file config/slam_toolbox_rf2o.yaml &

echo ""
echo "================================================"
echo "Stack running - LIDAR ONLY"
echo "Topics:"
echo "  /scan          (LIDAR)"
echo "  /map           (Generated by SLAM)"
echo ""
echo "Test with:"
echo "  rviz2 -d rviz_config.rviz"
echo "================================================"

wait
