CLaserOdometry2DNode:
  ros__parameters:
    laser_scan_topic: /scan
    odom_topic: /odom_rf2o
    base_frame_id: base_link
    odom_frame_id: odom
    init_pose_from_topic: ""
    
    # --- STABILISATION ---
    freq: 12.0                   # RÉDUIT: Calé sur la fréquence réelle du LiDAR
    publish_tf: true             # Doit être true pour que SLAM reçoive l'odométrie
    
    # --- LIMITES RÉALISTES ---
    max_linear_speed: 0.50       # On laisse de la marge
    max_angular_speed: 1.5       # On bride un peu pour la précision du mapping
    
    # --- OPTIMISATION ---
    # 300 itérations c'est trop, ça peut créer du lag CPU qui décale les scans. 
    # 30 à 50 itérations suffisent amplement si le LiDAR est propre.
    max_iterations: 50           
    tolerance: 1e-4              # 1e-7 est trop strict pour du bruit laser, 1e-4 est plus stable
    
    # --- FILTRES ANTI-DRIFT (Ajoute ces lignes si possible) ---
    motion_filter_linear: 0.01   # Seuil mini de mouvement (1cm)
    motion_filter_angular: 0.005 # Seuil mini de rotation (0.3°)