slam_toolbox:
  ros__parameters:
    use_sim_time: false

    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    scan_queue_size: 30
    throttle_scans: 2
    rviz_transmit_queue_size: 20

    resolution: 0.05
    min_laser_range: 0.12
    max_laser_range: 8.0

    transform_publish_period: 0.05
    map_update_interval: 0.5

    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.03
    minimum_travel_heading: 0.03

    scan_buffer_size: 20

    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 6
    loop_match_maximum_variance_queue_size: 5
    loop_match_minimum_response_fine: 0.1
    loop_match_minimum_response_coarse: 0.35

    publish_tf: true
    publish_pose_graph: false
    enable_interactive_mode: true
